### PR TITLE
fix: handle constructor and __proto__

### LINKED ISSUE #5: Handle correctly words constructor and __proto__

### PR DESCRIPTION
**Pull request by Ceres6**
closes #5

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
I must admit that I'm not very familiar with Object.create and how exactly it works around the issue that PR intends to address. Nevertheless, I would like to make sure that we're aware of the implications, so at the cost of saying something obvious I'll post my concerns and questions here:

- from the docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#using_propertiesobject_argument_with_object.create) (scroll down a little to the snippet that shows using `Object.create(null)`) it says that "By default properties are not writable, enumerable or configurable.". So, I know it's a stupid question so I wonder how this can possibly work
- from the docs[here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#null-prototype_objects), it looks like creating objects with null prototypes has all sorts of caveats, so I want to make sure we know what we're getting into by doing this

File: src/index.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ function recursivePositionInsertion<S extends PropertiesSchema>(
   prefix = "",
   schema: PropertiesSchema = lyra.schema,
 ) {
-  lyra.positions[id] = {};
+  lyra.positions[id] = Object.create(null, {});
```
Comment (simoneb) [inline src/index.ts:35]: is the second argument needed? genuine question, I'm not familiar with this syntax but from the docs I couldn't find an explanation why there would be a difference between providing it empty and not providing it at all

Comment (Eomm) [reply src/index.ts:35]: I agree https://devdocs.io/javascript/global_objects/object/create

By running `Object.getOwnPropertyDescriptors({})` there are not enumerable properties

Comment (Ceres6) [reply src/index.ts]: Second argument removed. Regarding prototype null the problem is that regular prototype object methods become inaccessible but we're not using them anyway so that shouldn't be a problem

Comment (simoneb) [reply src/index.ts]: > * from the docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#using_propertiesobject_argument_with_object.create) (scroll down a little to the snippet that shows using `Object.create(null)`) it says that "By default properties are not writable, enumerable or configurable.". So, I know it's a stupid question so I wonder how this can possibly work

@Ceres6 did you have a chance to look into this? I mean, the docs say that if you create an object like this, by default properties or not **writable**. I would assume that if we create an object whose properties are not writable, there isn't much that we can do with it. Clearly I would imagine that lots of test would break if this was the case, but still I would like to understand why this is working then. Are the docs wrong or what they say doesn't apply to us for some reason?

Comment (Ceres6) [reply src/index.ts]: Yes, it does only refer to properties declared in the creation. For example

```js
const a = Object.create(null, { b: { value: 3 } })  // b not writable

console.log(a)  // [Object: null prototype] {}
console.log(a.b)  // 3

a.b = 12  // throws in strict mode
console.log(a.b)  // still 3

a.c = 'Hello'  // correctly assigns
```

But that doesn't even refer only to null prototype object but to everything created that way (e.g. `Object.create({}, { b: { value: 3 } })`

Comment (simoneb) [reply src/index.ts]: ok that explains it, thanks

**Review by simoneb — APPROVED** [review]

**Review by micheleriva — APPROVED** [review]
lgtm
